version: '3.8'

services:
  react-app:
    build:
      context: ./my-react-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    
  flask-app:
    build:
      context: ./trello_backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"

